### ISSUE TITLE
Weird Transparency glitch on Intel Integrated Graphics

### ISSUE THREAD

**Issue by EriKWDev** [derivator/egui_vulkano#11]
![image](https://user-images.githubusercontent.com/19771356/186477356-8f15ee35-73c0-4fa4-b8dc-cbab9d2b8ff9.png)

Running on main branch's example. Getting reported info:
```yaml
> cargo run --release --example example
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
Using device: Intel(R) Xe Graphics (TGL GT2) (type: IntegratedGpu)

```

**Comment by derivator** [comment]
Looks a bit like #3. Are you running Wayland by any chance? You can check by running `echo $XDG_SESSION_TYPE` in terminal.

**Comment by EriKWDev** [comment]
Indeed wayland.

```yaml
> echo $XDG_SESSION_TYPE
wayland
```

Running on Fedora 36, with 5.18.18-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 17 16:02:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by derivator** [comment]
The common factors between #3 and this seem to be Wayland and Intel GPU. @Vistavleal suggested that xWayland might also be involved somehow, but they were unfortunately not in a position to try on x11. Meanwhile I could not reproduce this on Wayland/NVidia GPU. @EriKWDev could you test on x11?

**Comment by EriKWDev** [comment]
Getting the same on x11 actually:
![image](https://user-images.githubusercontent.com/19771356/186860004-109bd57c-366f-470f-8935-3771cc593b4e.png)


```yaml
> echo $XDG_SESSION_TYPE
x11
```

Seems like Intel Integrated Graphics might be the problem then.

**Comment by derivator** [comment]
Can you try running some of the [vulkano examples](https://github.com/vulkano-rs/vulkano/tree/master/examples/src/bin) and see if they have similar problems? If those work, then I have a suspicion: In #10 @Wicpar said that egui_vulkano currently does some things that are actually forbidden by the vulkan spec, which Vulkano 0.30 checks and rejects. It could be that the NVidia driver quietly fixes up the incorrect usage, whereas the Intel driver doesn't do that and just happily corrupts GPU memory instead. Maybe try his Vulkano 0.30 branch and see if that fixes it?

**Comment by EriKWDev** [comment]
I don't really knew what to look for, but I cloned vulkano and ran the `run_all` script in the examples directory and (after some compilation torture to my poor laptop) they all look fine to me (wayland):

![image](https://user-images.githubusercontent.com/19771356/186968818-6c124beb-d5c1-45a6-be9d-21490a565164.png)
![image](https://user-images.githubusercontent.com/19771356/186968849-caa001a0-f46b-4602-97ae-6628f5772cac.png)
![image](https://user-images.githubusercontent.com/19771356/186968898-2011c12d-1845-4209-b68e-69babccbe08c.png)
![image](https://user-images.githubusercontent.com/19771356/186968952-a38bfa28-c05e-4a32-abd3-2b3d36d2df62.png)
![image](https://user-images.githubusercontent.com/19771356/186969039-2e9caead-2d19-413c-9001-287cb88d9e86.png)
![image](https://user-images.githubusercontent.com/19771356/186969144-f73f25a3-89c8-4541-a9f3-09e27837f1ab.png)
---

I also tried out the main branch of @Wicpar's fork with vulkano 0.30 on wayland I got the following runtime error:
```yaml
Available layer: VK_LAYER_VALVE_steam_overlay_32
Available layer: VK_LAYER_VALVE_steam_overlay_64
Available layer: VK_LAYER_VALVE_steam_fossilize_32
Available layer: VK_LAYER_VALVE_steam_fossilize_64
Available layer: VK_LAYER_RENDERDOC_Capture
Available layer: VK_LAYER_MESA_device_select
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LayerNotPresent', examples/example.rs:64:8
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
   3: example::main

```
(link to line in fork: https://github.com/Wicpar/egui_vulkano/blob/02ca7f81df42ace9577f5c669e42d76b56c8112c/examples/example.rs#L60)

**Comment by derivator** [comment]
You can change this line:
 `enabled_layers: vec!["VK_LAYER_KHRONOS_validation".into()],`
to
`enabled_layers: vec![],`

That should allow you to run the fork.

**Comment by EriKWDev** [comment]
Eureka! On wayland using the fork:

![image](https://user-images.githubusercontent.com/19771356/186978873-e812697c-c359-4c9e-b6b7-22ed6b54b92a.png)

I now no longer see a triangle though, but haven't read th eexample enough yet to see if it was removed.

**Comment by derivator** [comment]
Thanks for testing! That seems to support my theory. The triangle is behind the gui, because at some point the egui example changed to fill the whole screen and I haven't bothered to change it :smile:

**Comment by EriKWDev** [comment]
Very nice to get it working though! 

Would be nice to get that fork merged :)

Would also be nice to see a Vulkan texture be rendered into an egui Image in the/an example!

But I suppose that's just supplying the image with an egui::TextureId::User(_) with a Vulkan texture handle..?

I will also be trying to get this working with glfw instead of winit since winit takes so long to compile...

Thanks for the awesome work and help debugging!

**Comment by derivator** [comment]
I do plan on merging it, but haven't gotten around to it yet. Would be interesting to see if you can get it running with glfw.

**Comment by EriKWDev** [comment]
Will base it on this implementation https://github.com/cohaereo/egui_glfw_gl

Will write on this repo if I succeed!
Might become an egui_glfw crate like the egui_winit..

**Comment by EriKWDev** [comment]
Was a bit more struggle than I first though. Vulkano seems to use ash whereas the vulkan feature of the glfw crate produces types compatible with vk-sys... Have to find some conversions to and from the types. Previous attempts seem dead but parts of them can probably be of use https://github.com/atwupack/vulkan4rust, https://gitlab.com/braxtons12/vulkano-glfw-v2
